name: jupiter_academy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  dio: ^5.7.0
  dropdown_button2: ^2.3.9
  encrypt: ^5.0.3
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.1.2
  flutter_rating_bar: ^4.0.1
  geolocator: 12.0.0
  google_fonts: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.0
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  intl: ^0.19.0
  mime: ^1.0.5
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.3
  slide_to_act: ^2.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
